"""Generated by the Placebo evaluation harness.

The provenance of each candidate is recorded above it. Whether a test is
oracle-admitted or merely a green baseline candidate is recorded separately in
the experiment results; this file does not make that claim on its own.
"""

import pytest
import semver




# fault detected: semver/version.py:598 in Version.match: `0` -> `1` (constant)
# mutant id: 7c644c64bde4883c
def test_placebo_01_version_match():
    """Detects: semver/version.py:598 in Version.match: `0` -> `1` (constant)"""
    assert repr(semver.Version.parse("1.0.0").match(">=1.0.0")) == 'True'


# fault detected: semver/version.py:730 in Version.is_compatible: `False` -> `None` (return_value)
# mutant id: 95f32034b4f97f3d
def test_placebo_02_version_is_compatible():
    """Detects: semver/version.py:730 in Version.is_compatible: `False` -> `None` (return_value)"""
    assert repr(semver.Version.parse("0.1.0").is_compatible(semver.Version.parse("0.0.1"))) == 'False'
    assert repr(semver.Version.parse("0.0.1").is_compatible(semver.Version.parse("0.1.0"))) == 'False'


# fault detected: semver/version.py:599 in Version.match: `0` -> `1` (constant)
# mutant id: bad59b17cefa1f72
def test_placebo_03_version_match():
    """Detects: semver/version.py:599 in Version.match: `0` -> `1` (constant)"""
    assert repr(semver.Version.parse("1.0.0").match("<=1.0.0")) == 'True'
    assert repr(semver.Version.parse("1.0.0").match("<=0.9.9")) == 'False'
    assert repr(semver.Version.parse("2.0.0").match("<=1.0.0")) == 'False'
    assert repr(semver.Version.parse("1.0.0").match("<=1.0.0-alpha")) == 'False'
    assert repr(semver.Version.parse("1.0.0").match("<=1.0.0+build.1")) == 'True'
