"""Generated by the Placebo evaluation harness.

The provenance of each candidate is recorded above it. Whether a test is
oracle-admitted or merely a green baseline candidate is recorded separately in
the experiment results; this file does not make that claim on its own.
"""

import pytest
import semver




# fault detected: semver/version.py:292 in Version.bump_minor: `1` -> `2` (constant)
# mutant id: 0311cef58a002912
def test_placebo_01_version_bump_minor():
    ver = semver.VersionInfo.parse("3.4.5")
    expected = semver.VersionInfo(major=3, minor=5, patch=0)
    assert ver.bump_minor() == expected


# fault detected: semver/version.py:483 in Version.__gt__: `>` -> `>=` (comparison_boundary)
# mutant id: 085c382c12637d90
def test_placebo_02_version___gt():
    version1 = semver.VersionInfo.parse("1.0.0")
    version2 = semver.VersionInfo.parse("1.0.0")

    # The correct implementation returns False for equality
    assert not version1 > version2

    # The incorrect implementation returns True for equality
    assert version1 >= version2 and not (version1 > version2)


# fault detected: semver/version.py:580 in Version.match: `0` -> `1` (constant)
# mutant id: 05cc88d0e0cba70d
def test_placebo_03_version_match():
    version = semver.Version.parse("1.0.0")
    match_expr = ">1.0.0"
    
    # Correct behavior: should return False because it's not greater than 1.0.0
    assert not version.match(match_expr)
