"""Generated by the Placebo evaluation harness.

The provenance of each candidate is recorded above it. Whether a test is
oracle-admitted or merely a green baseline candidate is recorded separately in
the experiment results; this file does not make that claim on its own.
"""

import pytest
import semver




# fault detected: semver/version.py:292 in Version.bump_minor: `1` -> `2` (constant)
# mutant id: 0311cef58a002912
def test_placebo_01_version_bump_minor():
    ver = semver.VersionInfo.parse("3.4.5")
    expected = semver.VersionInfo(major=3, minor=5, patch=0)
    assert ver.bump_minor() == expected


# fault detected: semver/version.py:554 in Version.finalize_version: `cls(self.major, self.minor, self.patch)` -> `None` (return_value)
# mutant id: 0723feea7643f22a
def test_placebo_02_version_finalize_version():
    version1 = semver.Version.parse('1.2.3-rc.5')
    version2 = semver.Version.parse('1.2.3')

    assert str(version1.finalize_version()) == '1.2.3'
    assert version1.finalize_version() != None


# fault detected: semver/version.py:514 in Version.__getitem__: `and` -> `or` (boolean_logic)
# mutant id: 2efccfe40d947649
def test_placebo_03_version___getitem():
    ver = semver.Version.parse("3.4.5")
    
    # Test with negative slice start
    try:
        part = ver[-1:0]
        assert False, "Expected IndexError but got no exception"
    except IndexError:
        pass
    
    # Test with positive slice start and stop
    part = ver[0:2]
    assert part == (3, 4)


# fault detected: semver/version.py:483 in Version.__gt__: `>` -> `>=` (comparison_boundary)
# mutant id: 085c382c12637d90
def test_placebo_04_version___gt():
    version1 = semver.VersionInfo.parse("1.0.0")
    version2 = semver.VersionInfo.parse("1.0.0")

    # The correct implementation returns False for equality, but the regression
    # changes it to return True.
    assert not version1 > version2


# fault detected: semver/version.py:580 in Version.match: `0` -> `1` (constant)
# mutant id: 05cc88d0e0cba70d
def test_placebo_05_version_match():
    version = semver.Version.parse("1.0.0")
    match_expr = ">1.0.0"
    
    # Correct behavior: should return False
    assert not version.match(match_expr)

    match_expr = "<1.0.0"
    
    # Correct behavior: should return False
    assert not version.match(match_expr)
