"""Generated by the Placebo evaluation harness.

The provenance of each candidate is recorded above it. Whether a test is
oracle-admitted or merely a green baseline candidate is recorded separately in
the experiment results; this file does not make that claim on its own.
"""

import pytest
import semver




# fault detected: semver/version.py:292 in Version.bump_minor: `1` -> `2` (constant)
# mutant id: 0311cef58a002912
def test_placebo_01_version_bump_minor():
    ver = semver.Version.parse("3.4.5")
    expected_version = semver.Version(major=3, minor=5, patch=0, prerelease=None, build=None)
    actual_version = ver.bump_minor()
    assert actual_version == expected_version


# fault detected: semver/version.py:554 in Version.finalize_version: `cls(self.major, self.minor, self.patch)` -> `None` (return_value)
# mutant id: 0723feea7643f22a
def test_placebo_02_version_finalize_version():
    version = semver.Version.parse('1.2.3-rc.5')
    assert str(version.finalize_version()) == '1.2.3'


# fault detected: semver/version.py:483 in Version.__gt__: `>` -> `>=` (comparison_boundary)
# mutant id: 085c382c12637d90
def test_placebo_03_version___gt():
    # Define a version object and an equivalent version for comparison
    v1 = semver.VersionInfo.parse("1.0.0")
    v2 = semver.VersionInfo.parse("1.0.0")

    # The correct implementation should return False because the versions are equal
    assert not v1.__gt__(v2)


# fault detected: semver/version.py:580 in Version.match: `0` -> `1` (constant)
# mutant id: 05cc88d0e0cba70d
def test_placebo_04_version_match():
    version = semver.Version.parse("2.0.0")
    assert version.match(">1.0.0") == True
    assert version.match("<3.0.0") == True
    assert version.match(">=2.0.0") == True
    assert version.match("<=2.0.0") == True
    assert version.match("==2.0.0") == True
    assert version.match("!=1.0.0") == True
