"""Build a blinded reviewer study packet.

Status, stated plainly: **the instrument is built; the study has not been run.**
No human ratings exist, and none are reported anywhere in this project. Shipping
the instrument without the data is the honest option - it makes the protocol
auditable and the study cheap for someone else to run, without inventing
results.

What this produces
------------------
A packet a reviewer can complete in about fifteen minutes:

* every candidate patch, stripped of any marker identifying which condition
  produced it, and shuffled under a fixed seed;
* a key file (kept separate) mapping blind labels back to conditions;
* a rating form with the questions that actually matter to a tech lead.

Blinding matters here more than usual. The conditions produce visibly different
test *shapes* - oracle-grounded tests assert `repr(...)`, search-derived tests
use boundary values - so an unblinded rater could infer the condition and score
the narrative rather than the test.

Usage:
  python scripts/build_review_study.py
"""

from __future__ import annotations

import json
import random
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from placebo.mutation.models import write_json  # noqa: E402

OUT = ROOT / "artifacts" / "review-study"
SEED = 20260831

CANDIDATES = {
    "baseline_A": "artifacts/suites/baseline_A.py",
    "placebo_B": "artifacts/suites/placebo_B.py",
    "placebo_C": "artifacts/suites/placebo_C.py",
    "placebo_D": "artifacts/suites/placebo_D.py",
    "search_gap_patch": "artifacts/suites/search_gap_patch.py",
    "real_gap_patch": "artifacts/suites/real_gap_patch.py",
}

# Markers that would leak the producing condition to a rater.
_LEAKS = [
    (re.compile(r"^\s*#\s*(fault detected|evaluation case|mutant id).*$", re.M), ""),
    (re.compile(r"\bplacebo\b", re.I), "generated"),
    (re.compile(r"\btest_placebo_\d*_?", re.I), "test_case_"),
    (re.compile(r'"""Generated by.*?"""', re.S), '"""Candidate tests."""'),
    (re.compile(r"Input found by deterministic counterexample search;?", re.I), ""),
    (re.compile(r"observed by executing the reference implementation\.?", re.I), ""),
]

FORM = """# Blinded review form

You are reviewing {n} candidate test patches for `python-semver`. You do not
know which tool or process produced any of them, and the order is randomized.

For **each** patch, please record:

| # | question | scale |
|---|---|---|
| 1 | Would you merge this as-is? | yes / with changes / no |
| 2 | Is it readable? | 1 (poor) - 5 (excellent) |
| 3 | Does it capture behavior worth protecting? | 1 - 5 |
| 4 | Would it catch a realistic future regression? | 1 - 5 |
| 5 | How confident are you in answers 1-4? | 1 - 5 |
| 6 | Minutes spent reviewing this patch | integer |

Free text, per patch:

- What is the strongest test here, and why?
- What is the weakest, and why?
- Anything that would make you reject the patch outright?

## Rules

- Review in the order given. Do not skip ahead.
- Do not run the tests. Judge them as a reviewer reading a pull request.
- Record minutes honestly, including time spent confused.
- If you recognize a patch's origin, say so - it means blinding failed.

## Patches

{listing}

Return the completed form to the study coordinator. Ratings are analyzed with
`scripts/analyze_review_study.py`, which unblinds only after all ratings are in.
"""

ANALYSIS_STUB = '''"""Analyze blinded reviewer ratings.

Run only after every reviewer has returned a completed form. Reads
`artifacts/review-study/ratings/*.json`, joins them to `key.json`, and reports
per-condition medians with a paired comparison across reviewers.

No ratings have been collected, so this script currently reports that and exits.
It exists so the analysis is fixed *before* any data arrives, which is the point
of pre-registering an instrument.
"""

from __future__ import annotations

import json
import statistics
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STUDY = ROOT / "artifacts" / "review-study"


def main() -> int:
    ratings_dir = STUDY / "ratings"
    files = sorted(ratings_dir.glob("*.json")) if ratings_dir.exists() else []
    if not files:
        print("No reviewer ratings collected.")
        print(f"Expected: {ratings_dir.relative_to(ROOT)}/<reviewer>.json")
        print("The instrument is built; the study has not been run. No human")
        print("acceptance numbers are claimed anywhere in this project.")
        return 0

    key = json.loads((STUDY / "key.json").read_text(encoding="utf-8"))
    by_condition: dict[str, list[float]] = {}
    for path in files:
        for label, scores in json.loads(path.read_text(encoding="utf-8")).items():
            condition = key.get(label, "unknown")
            by_condition.setdefault(condition, []).append(scores["would_merge"])

    print(f"{len(files)} reviewer(s)\\n")
    for condition, values in sorted(by_condition.items()):
        print(f"  {condition:<20} median merge score "
              f"{statistics.median(values):.2f}  n={len(values)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def blind(code: str) -> str:
    for pattern, replacement in _LEAKS:
        code = pattern.sub(replacement, code)
    # Collapse the blank lines left behind by stripped comments.
    return re.sub(r"\n{3,}", "\n\n", code).strip() + "\n"


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "patches").mkdir(exist_ok=True)

    available = [(name, ROOT / rel) for name, rel in CANDIDATES.items()
                 if (ROOT / rel).exists() and "def test_" in (ROOT / rel).read_text(encoding="utf-8")]
    if not available:
        print("no candidate patches found")
        return 1

    rng = random.Random(SEED)
    order = list(available)
    rng.shuffle(order)

    key, listing = {}, []
    for index, (condition, path) in enumerate(order, 1):
        label = f"patch_{index:02d}"
        blinded = blind(path.read_text(encoding="utf-8"))
        (OUT / "patches" / f"{label}.py").write_text(blinded, encoding="utf-8")
        key[label] = condition
        listing.append(f"- `patches/{label}.py`")

    (OUT / "REVIEW_FORM.md").write_text(
        FORM.format(n=len(order), listing="\n".join(listing)), encoding="utf-8"
    )
    write_json(OUT / "key.json", key)
    (ROOT / "scripts" / "analyze_review_study.py").write_text(
        ANALYSIS_STUB, encoding="utf-8"
    )

    print("=" * 70)
    print("  BLINDED REVIEWER STUDY - instrument built, study NOT run")
    print("=" * 70)
    print(f"  patches prepared : {len(order)} (condition markers stripped, shuffled)")
    print(f"  form             : {(OUT / 'REVIEW_FORM.md').relative_to(ROOT)}")
    print(f"  key (do not show : {(OUT / 'key.json').relative_to(ROOT)}")
    print(f"    to reviewers)")
    print(f"  analysis         : scripts/analyze_review_study.py")
    print("=" * 70)
    print("  No human ratings exist. No acceptance rate is claimed anywhere in")
    print("  this project. The instrument ships so the protocol is auditable")
    print("  and the study is cheap for someone else to run.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
